apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qyvt8kfgy-python
  janus-idp.io/tekton: qyvt8kfgy-python
  backstage.io/kubernetes-id: qyvt8kfgy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qyvt8kfgy-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
