apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qyvt8kfgy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qyvt8kfgy-python 
  name: qyvt8kfgy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qyvt8kfgy-python 
